name: MiniCPMV
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - pillow
  - scipy
  - scikit-learn
  - nltk

  - pip:
    - absl-py==2.1.0
    - accelerate==0.33.0
    - aiofiles==23.2.1
    - annotated-types==0.7.0
    - anyio==4.4.0
    - bert-score==0.3.13
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - click==8.1.7
    - git+https://github.com/openai/CLIP.git
    - clip-score==0.1.1
    - contourpy==1.2.1
    - cycler==0.12.1
    # - deepspeed==0.14.5
    - exceptiongroup==1.2.2
    - fastapi==0.112.1
    - ffmpy==0.4.0
    - filelock==3.13.1
    - fonttools==4.53.1
    - fsspec==2024.2.0
    - ftfy==6.2.3
    - gradio==4.42.0
    - gradio-client==1.3.0
    - grpcio==1.66.0
    - h11==0.14.0
    - hjson==3.1.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.24.6
    - idna==3.7
    - importlib-resources==6.4.4
    - jinja2==3.1.3
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - mdurl==0.1.2
    - mpmath==1.3.0
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nltk==3.9.1
    - numpy==1.26.3
    - orjson==3.10.7
    - packaging==24.1
    - peft==0.12.0
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.8
    - pydantic==2.8.2
    - pydantic-core==2.20.1
    - pydub==0.25.1
    - pygments==2.18.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.9
    - pytz==2024.1
    - pyyaml==6.0.2
    - regex==2024.7.24
    - requests==2.32.3
    - rich==13.7.1
    - ruff==0.6.2
    - safetensors==0.4.4
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - setuptools==72.1.0
    - shellingham==1.5.4
    - six==1.16.0
    - sniffio==1.3.1
    - starlette==0.38.2
    - sympy==1.12
    - tensorboard==2.17.1
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - timm==1.0.8
    - tokenizers==0.15.2
    - tomlkit==0.12.0
    - tqdm==4.66.5
    - transformers==4.36.0
    - typer==0.12.4
    - typing-extensions==4.9.0
    - tzdata==2024.1
    - urllib3==2.2.2
    - uvicorn==0.30.6
    - wcwidth==0.2.13
    - websockets==12.0
    - werkzeug==3.0.4
    - wheel==0.43.0

# NOTE:
# 1) This file was cleaned for Windows (win-64). Platform-specific low-level packages
#    and Linux-only build pins have been removed (e.g. _openmp_mutex, ld_impl_linux-64,
#    libgcc-ng, libgomp, many nvidia/* entries, torch+cu* wheels, triton, prefix).
# 2) PyTorch (torch / torchvision / torchaudio) and CUDA-related packages are NOT included
#    here. Install PyTorch separately after creating the environment using commands tailored
#    to your machine's CUDA/drivers (examples below).
# 3) If you plan to run on Linux (WSL2 / VM / native), or want an "exact" reproduction,
#    consider using the original environment on Linux or re-exporting with `--from-history`.
